-- Add new category values to the Category enum
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'POWER_ADAPTOR';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'WIFI_RECEIVER';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'THREE_PIN';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'VGA_CABLE';
ALTER TYPE "Category" ADD VALUE IF NOT EXISTS 'HDMI_CABLE';
